### ISSUE TITLE
Redmine 6.x support

### ISSUE THREAD

**Issue by mshr-hsgw** [maedadev/redmine_backlogs#34]
Trying to install on Redmine6, we found that the method called “unloadable” in the library called activesupport used in the Backlogs plugin code has been deprecated since Rails7, and the current code of Backlogs could not be installed on Redmine6 which is implemented in Rails7.
Is there any plan to support Redmine 6.x?

**Comment by ichylinux** [comment]
hi, @mshr-hsgw 

we just adapted Backlogs plugin to Redmine-5.1, currently.

so, the next will be Redmine 6, but we don't have any concrete time schedule for it.

**Comment by dobrildobrilov** [comment]
With few simple patches it's working fine with Redmine 6.0.6(latest)

**Comment by acmea24-oss** [comment]
Where can i get patched version? 
Im still getting this `unloadable' 
Redmine 6.0.6.stable

rake aborted!
NameError: undefined local variable or method `unloadable' for Issue:Class
/usr/local/bundle/ruby/3.1.0/gems/activerecord-7.2.2.1/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
/usr/src/redmine/plugins/redmine_backlogs/lib/backlogs_issue_patch.rb:10:in `block in included'
/usr/src/redmine/plugins/redmine_backlogs/lib/backlogs_issue_patch.rb:9:in `class_eval'
/usr/src/redmine/plugins/redmine_backlogs/lib/backlogs_issue_patch.rb:9:in `included'
/usr/src/redmine/plugins/redmine_backlogs/lib/backlogs_issue_patch.rb:210:in `include'
/usr/src/redmine/plugins/redmine_backlogs/lib/backlogs_issue_patch.rb:210:in `<top (required)>'
/usr/src/redmine/plugins/redmine_backlogs/init.rb:23:in `require_relative'
/usr/src/redmine/plugins/redmine_backlogs/init.rb:23:in `block in <top (required)>'

**Comment by dobrildobrilov** [comment]
> Where can i get patched version? Im still getting this `unloadable' Redmine 6.0.6.stable
> 
> rake aborted! NameError: undefined local variable or method `unloadable' for Issue:Class /usr/local/bundle/ruby/3.1.0/gems/activerecord-7.2.2.1/lib/active_record/dynamic_matchers.rb:22:in `method_missing' /usr/src/redmine/plugins/redmine_backlogs/lib/backlogs_issue_patch.rb:10:in `block in included' /usr/src/redmine/plugins/redmine_backlogs/lib/backlogs_issue_patch.rb:9:in `class_eval' /usr/src/redmine/plugins/redmine_backlogs/lib/backlogs_issue_patch.rb:9:in `included' /usr/src/redmine/plugins/redmine_backlogs/lib/backlogs_issue_patch.rb:210:in `include' /usr/src/redmine/plugins/redmine_backlogs/lib/backlogs_issue_patch.rb:210:in `<top (required)>' /usr/src/redmine/plugins/redmine_backlogs/init.rb:23:in `require_relative' /usr/src/redmine/plugins/redmine_backlogs/init.rb:23:in `block in <top (required)>'

https://github.com/dobrildobrilov/redmine_backlogs.git
